version: "3.9"
services:
  nginx:
    image: nginx:1.21.0
    volumes:
      - ./mirrulations-nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - dashboard
    logging:
      driver: "local"
      options:
        max-size: "10m"
  redis:
    image: redis:6.2.4
    volumes:
      - "~/data/redis:/data"
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      driver: "local"
      options:
        max-size: "10m"
  rabbitmq:
    build:
      context: .
      dockerfile: mirrulations-rabbitmq/Dockerfile
    hostname: 'mirrulations-rabbitmq'
    volumes:
      - "~/data/rabbitmq:/var/lib/rabbitmq/mnesia"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      driver: "local"
      options:
        max-size: "10m"
  work_generator:
    build:
      context: .
      dockerfile: mirrulations-work-generator/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file: env_files/work_gen.env
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  validator:
    build:
      context: .
      dockerfile: mirrulations-validation/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file: env_files/validator.env
    restart: always
    volumes:
      - "~/data/validator:/data/validator"
      - "~/data/data:/data/data"
    logging:
      driver: "local"
      options:
        max-size: "10m"
  extractor:
    build:
      context: .
      dockerfile: mirrulations-extractor/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    env_file: env_files/extractor.env
    restart: always
    volumes:
      - "~/data/data:/data"
    logging:
      driver: "local"
      options:
        max-size: "10m"
  dashboard:
    build:
      context: .
      dockerfile: mirrulations-dashboard/Dockerfile
    env_file: env_files/dashboard.env
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client1:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client1.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client2:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client2.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client3:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client3.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client4:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client4.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client5:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client5.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client6:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client6.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client7:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client7.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client8:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client8.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client9:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client9.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client10:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client10.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client11:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client11.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client12:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client12.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client13:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client13.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client14:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client14.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client15:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client15.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client16:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client16.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client17:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client17.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client18:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client18.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client19:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client19.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client20:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client20.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client21:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client21.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client22:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client22.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client23:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client23.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client24:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client24.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
  client25:
    build:
      context: .
      dockerfile: mirrulations-client/Dockerfile
    env_file: env_files/client25.env
    volumes:
      - ~/data/data:/data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
